language: csharp
solution: ./XpdfNet.sln
mono: none
dotnet: 1.0.4
dist: trusty

os:
  - linux
  - osx

install:
  - ulimit -n 2048; dotnet restore ./XpdfNet.sln

script:
  - dotnet test ./src/XpdfNet.Tests/XpdfNet.Tests.csproj -f netcoreapp1.1
