image: Visual Studio 2017
configuration: Release

environment:
  dotnetcore_version: 1.0.3
  CODECOV_TOKEN:
    secure: XxAwta0CJROTWAW5GFA83PnTXrGHcyJs7KDBOQNkntfkhydKHYjL+oAVGx5lXv6c

before_build:
  - nuget restore

build:
  project: XpdfNet.sln

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# run unit tests
test_script:
- C:\Users\appveyor\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:test .\XpdfNet.Tests\XpdfNet.Tests.csproj" -output:".\coverage.xml" -filter:"+[XpdfNet*]* -[XpdfNet.Tests*]* -[xunit*]*" -oldstyle -returntargetcode

- ps: $env:APPVEYOR_REPO_COMMIT
- ps: $env:APPVEYOR_REPO_BRANCH
- ps: $env:APPVEYOR_REPO_COMMIT_AUTHOR
- ps: $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps: $env:APPVEYOR_REPO_COMMIT_MESSAGE


- ps: $env:APPVEYOR_BUILD_NUMBER

- after_test:
- ps: .\nuget\pack.ps1
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"

artifacts:
  - path: '*.nupkg'
    name: XpdfNet

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
    # Deploying to a named environment
  - provider: NuGet
    api_key:
      secure: Wrkxnbucd5TOMxg4b0JjpgexOfRlxd9gmm8XKZnjUTjn2H1uvfnVSoV6jbmkwUre
    artifact: /.*\.nupkg/
    on:
      branch: master

# clear github badge cache
#on_success:
#- curl -X PURGE https://camo.githubusercontent.com/b5a05a66dcd05757f3624da408ea0e5a243cc4f5/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f6771793131372f576562546f6f6c2f62616467652e7376673f6272616e63683d6d61737465722631
on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))